### ISSUE TITLE
Error while running high level client.

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#100]
(node:3959) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Invalid ResourceInit
(node:3959) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gabrielschulhof** [comment]
It sounds like you're not doing
```JS
(...).then( function() { /* ... success ... */ }, function() { /* ... error ... */ } );
```
but only
```JS
(...).then( function() { /* ... success ... */ } );
```
in response to a promise. If you only provide the first function, then the error goes unhandled, and will cause an exit with a fatal error in future node.js versions.

**Comment by gabrielschulhof** [comment]
In this case the error is occurring because the resource you wish to register does not pass [validation](https://github.com/otcshare/iotivity-node/blob/1.2.0-0/lib/payload.js#L55).

**Comment by iamsanjeev** [comment]
Bingo! Problem solved.
