### ISSUE TITLE
Simple NativeClient NodejsServer Test Fails (1.2.0)

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#101]
Native client with the following code.
rt = "oic.d.ivi"
URI = "/a/vehicle/control"

if ( device.device.uuid ) {

	console.log( "Registering OCF resource" );

	device.server.register( {
		resourcePath: "/a/vehicle/control",
		resourceTypes: [ "oic.d.ivi" ],
		"if": [ "oic.if.baseline" ],
		discoverable: true,
		observable: true,
		properties: { user: 0 , scene: 0 }
	} ).then(
		function( resource ) {
			console.log( "OCF resource successfully registered" + resource.resourcePath);
			carResource = resource;

			// Add event handlers for each supported request type
			_.each( vehicleHandlers, function( callback, requestType ) {
				resource[ "on" + requestType ]( function( request ) {
					console.log( "Received request " + JSON.stringify( request, null, 4 ) );
					callback( request );
				} );
			} );
		},
		function( error ) {
			throw error;
		} );
}

Discovery from client is OK

Matched out Resource Type oic.d.ivi
Device Type = 0 /a/vehicle/control
ServerID Found b80c0ea2-dfbb-4507-8ac7-dc89167bd057 Assigned SID b80c0ea2-dfbb-4507-8ac7-dc89167bd057
Finding Resource.../oic/res 
Resource Found /a/vehicle/control Assigned b80c0ea2-dfbb-4507-8ac7-dc89167bd057

Now client tries to PUT
OCRepresentation rep;
rep.setValue<int>("scene", s->user);
rep.setValue<int>("user",  s->scene);
resource->put(rep, QueryParamsMap(), &onPut);

And result is 

PUT /a/vehicle/control
Completed Posting
**CALLBACK**  PUT request response code = **132**

**Comment by gabrielschulhof** [comment]
PUT is used for creating new resources, not updating existing ones.

According to the OIC Core Specification v1.1 line 2597, updating an
existing resource is to be done with POST, not PUT.

**Comment by iamsanjeev** [comment]
ok, and on server side it is "create" ?

**Comment by gabrielschulhof** [comment]
POST with just properties is "update".
POST with a full resource is "create".
PUT is "create".

**Comment by iamsanjeev** [comment]
Yes. it works as advertised now :+1:  Thanks Gabriel.

**Comment by gabrielschulhof** [comment]
Glad to hear it :)
