### ISSUE TITLE
[osx] Build failure

### ISSUE THREAD

**Issue by poussa** [otcshare/iotivity-node#107]
OSX 10.12.2 and Xcode 8.2.1 

`npm install` fails 

```
ld: library not found for -lconnectivity_abstraction
```

**Comment by wind-rider** [comment]
please try with a clean checkout and the modifications I made in https://github.com/otcshare/iotivity-node/pull/116

**Comment by poussa** [comment]
Works for me now on OSX 10.12.3 with Xcode 8.2.1

Thanks!
