### ISSUE TITLE
Property "target" should return object "ResourceId" rather than "Resource"

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#108]
[Spec](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#resource) defined the property `target` should return object [`ResourceId`](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md/#resourceid). The object `ResourceId` only has two properties `deviceId` and `resourcePath`, but `request.target` returns object `resource` rather than `ResourceId` in implementation, for example test [`Retrieve - Resource/server.js`](https://github.com/01org/iot-js-api/blob/master/tests/Retrieve%20-%20Resource/server.js#L50).  Property `source` has same issue as `target`.

**Comment by zolkis** [comment]
The spec says `Resource` _extends_ `ResourceId, hence a `Resource` object can be passed everywhere where a `ResourceId` is required. This is by design.
