### ISSUE TITLE
Build failure with Windows 10 with the latest node.js

### ISSUE THREAD

**Issue by jvalsam** [otcshare/iotivity-node#118]
npm intall fails

 Checking out files: 100% (3277/3277), done.
  D:\Dropbox\PhD\Development\Puppy\iotivity-node\patches\0000-windows-dll-def-missing-symbols.patch:9: trailing whitespace.
  OCRepPayloadSetIntArray
  D:\Dropbox\PhD\Development\Puppy\iotivity-node\patches\0000-windows-dll-def-missing-symbols.patch:10: trailing whitespace.
  OCRepPayloadSetBoolArray
  D:\Dropbox\PhD\Development\Puppy\iotivity-node\patches\0000-windows-dll-def-missing-symbols.patch:11: trailing whitespace.
  OCRepPayloadSetStringArray
  D:\Dropbox\PhD\Development\Puppy\iotivity-node\patches\0000-windows-dll-def-missing-symbols.patch:12: trailing whitespace.
  OCRepPayloadSetDoubleArray
  D:\Dropbox\PhD\Development\Puppy\iotivity-node\patches\0000-windows-dll-def-missing-symbols.patch:13: trailing whitespace.
  OCRepPayloadSetPropObjectArray
CUSTOMBUILD : error : patch failed: resource/csdk/octbstack_product.def:102 [D:\Dropbox\PhD\Development\Puppy\iotivity-node\build\csdk.vcxproj]
CUSTOMBUILD : error : resource/csdk/octbstack_product.def: patch does not apply [D:\Dropbox\PhD\Development\Puppy\iotivity-node\build\csdk.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Dropbox\PhD\Development\Puppy\iotivity-node
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iotivity-node@1.2.0-2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iotivity-node@1.2.0-2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iotivity-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dropbox\PhD\Development\Puppy\iotivity-node\npm-debug.log

**Comment by gabrielschulhof** [comment]
What version of git do you have?

**Comment by gabrielschulhof** [comment]
I have
```
>git --version
git version 2.11.0.windows.1
```
and it applies the patches without complaint.

**Comment by jvalsam** [comment]
I have
git version 2.11.1.windows.1

**Comment by jvalsam** [comment]
I tried by installing the version 2.11.0.windows.1 but it doesn't work too.

**Comment by gabrielschulhof** [comment]
I think you may have your git line endings settings wrong. The "trailing whitespace" may be the \r that Windows line endings have.

In my [video](https://youtu.be/RgsZpv8IrWA?t=192) I show that you must install git such that, when given the choice, you select "Checkout as-is, commit Unix-style line endings".

**Comment by gabrielschulhof** [comment]
@jvalsam [this SO post](http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows) looks relevant. You can also `git config` without `--global` to only affect your repo, rather than all repos managed locally by your git.

**Comment by jvalsam** [comment]
Thank you! Problem solved!
During the intallation of git (2.11.0.windows.1), in case you choose
"Use Git from the Windows Command Prompt", then it skips the step 
of "configuring the line ending conversions".
I chose "Use Git and optional Unix tools from the Windows Command Prompt",
then "Checkout as-is, commit Unix-style line endings" and then go back to 
choose the "Use Git from the Windows Command Prompt".
