### ISSUE TITLE
NPM package version

### ISSUE THREAD

**Issue by wind-rider** [otcshare/iotivity-node#121]
Can anybody comment on how / when the npm package version is raised?

Today the OCF spec in Device.js was modified in master; I'd say this needs a changed package version?

**Comment by gabrielschulhof** [comment]
The version structure is <iotivity
version>-<nth-release-against-a-given-iotivity-version>. So, unless we port
ioivity-node to a new version of iotivity, we increase the latter part.
Otherwise, we increase the iotivity-version and reset the latter part to 0.
