### ISSUE TITLE
findResources() gets 4 resources even there is no OCF server running

### ISSUE THREAD

**Issue by qiuzhong** [otcshare/iotivity-node#127]
For iotivity-node-1.2.0-2, when there is no OCF server running, <code>findResources</code> still gets 4 resources with the href:
* /oic/sec/doxm
* /oic/sec/pstat
* /oic/d
* /oic/p

```
# curl http://127.0.0.1:8000/api/oic/res
[{"di":"35e24438-36bc-4a31-af43-de4277647713","links":[{"href":"/oic/sec/doxm","rt":"oic.r.doxm","if":"oic.if.baseline"}]},{"di":"35e24438-36bc-4a31-af43-de4277647713","links":[{"href":"/oic/sec/pstat","rt":"oic.r.pstat","if":"oic.if.baseline"}]},{"di":"35e24438-36bc-4a31-af43-de4277647713","links":[{"href":"/oic/d","rt":"oic.wk.d","if":"oic.if.baseline"}]},{"di":"35e24438-36bc-4a31-af43-de4277647713","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.baseline"}]
```

For iotivity-node-1.1.1-3, it will return just <strong>[]</strong>

These resources can still be discovered if there are any other OCF servers running. Not sure if this change comply the spec.

**Comment by gabrielschulhof** [comment]
Since we no longer specify whether the stack is to run in client mode or whether it is to run in server mode, I have no choice but to start the lowlevel stack with `OCInit(null, 0, OC_CLIENT_SERVER)`. This means that even if you just start a client, there will be a server on the network, that will have some default resources. When you then call `findResources()` the client discovers the resources it itself exposes.

**Comment by zolkis** [comment]
This is a bug in the spec. I filed an [issue](https://github.com/01org/iot-js-api/issues/36).

**Comment by zolkis** [comment]
I guess in client mode we'd expect to have an object without the `server` and `platform` properties. 
I propose adding an `init(mode)` and a `stop()` function. 
Why not a parameter to `require`? 
1. As the spec says, in some implementations the `ocf` object may be attached to a global object. 
2. Theoretically a script may decide to start in client mode, and later provide a server functionality that depends on the findings in client mode.
What do you say?
