### ISSUE TITLE
param type mismatch in OCCreateResource

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#130]
Both resource type and interface type parameters for creating a resource are arrays as per spec. 
But the API takes in String params.

**Comment by gabrielschulhof** [comment]
This is by design. The implementation takes the first type/interface and passes it to `OCCreateResource` and then takes all subsequent types/interfaces and passes them to `OCBindResourceTypeToResource` resp. `OCBindInterfaceToResource`.
