### ISSUE TITLE
Fix line endings

### ISSUE THREAD

**Issue by wind-rider** [otcshare/iotivity-node#131]
The line endings used in this repo cause a problem for windows users (CRLF is standard on windows, repo expects LF).

Assuming all files are text files in the repos, I think it would help to add a `.gitattributes` file with
```
* text eol=lf
```

to the iotivity-node repo and to the iotivity-native repos.

This makes that people don't have to fix the line endings behavior on their own machines.

Source: https://help.github.com/articles/dealing-with-line-endings/

**Comment by gabrielschulhof** [comment]
I can certainly add this to this repo, but you'll have to file a bug with [iotivity](https://jira.iotivity.org/) to get them to add a `.gitattributes` to their repo.

I the meantime, on Windows I [recommend](https://www.youtube.com/watch?v=RgsZpv8IrWA&t=192) that you tell git to force the use of lf.
