### ISSUE TITLE
Discussion: Next version

### ISSUE THREAD

**Issue by gabrielschulhof** [otcshare/iotivity-node#132]
@iamsanjeev, @wind-rider, @rzr, @nagineni, @poussa, @micrcx

What would you like to see in the next version of iotivity-node?

Since 1.2.0-2, I now have the followings:

* [dev](https://github.com/gabrielschulhof/iotivity-node/tree/dev):
  * A fairly significant reduction in installed size (8 MB →4.1 MB) by breaking up the lodash dependency to dependencies on individual lodash facilities that the code actually uses.
  * The `types` array on `ocf.device` is exposed and can be set at runtime.
  * `SECURED=1` continues to wait in the wings. It works but there is no support for bootstrapping/onboarding/ownership transfer. Everything needs to be done via `json2cbor`.
* [1.2.1](https://github.com/gabrielschulhof/iotivity-node/tree/1.2.1):
  * Support for 1.2.1.

Some questions regarding the new release:
* Which of the above should be included?
* Would you like to see in the new release anything I haven't listed above?
* Once we have a decision for the above, should I just make a branch here for you to test (like maintenance), or should I publish a beta version? I learned that you can publish a beta version with `npm publish --tag beta` and then whatever you publish will not be considered the latest version even if it is a later version than whatever was available.

**Comment by wind-rider** [comment]
Personally, I think that at least a part of the lodash calls might be not needed if iotivity-node would be written in TypeScript or a more recent version of ecmascript. The code could then be compiled to es5 (IIRC that is the needed target?).

That way you could make the code more readable and less dependent on lodas.
- declare "real" classes
- use class properties ([avoiding _.extend](https://github.com/gabrielschulhof/iotivity-node/blob/master/lib/Request.js#L79))
- use [get accessors](https://www.typescriptlang.org/docs/handbook/classes.html#accessors) ([instead of Object.defineProperty](https://github.com/gabrielschulhof/iotivity-node/blob/master/lib/ServerResource.js#L71-L74))

**Comment by gvancuts** [comment]
How far are we from being able to use `SECURED=1`? With the focus and emphasis out there on security, it would be good to be able to use it at some point. If not enabled by default, could that be turned on at install time using a flag or something?

Do you have some info on how to do the bootstrapping/onboarding/ownership transfer?

**Comment by rzr** [comment]
Hi,
FYI, I shared iotivity-1.2.1 for yocto's meta-oic to @kmaloor and kept security=0 (as aligned to upstream)...

but for upcoming 1.3 (I have also WIP yocto recipe) SECURITY will be be turned on, it would be nice to support it by default.

So I would suggest to create 1.2-rel and 1.3-rel branches for that.

My 2cents.

**Comment by gabrielschulhof** [comment]
@gvancuts I have tried the ownership transfer samples about a month ago and they didn't work. Even if they work now, we have no spec for a JS security API, so I could do the bindings, but it would basically be the C API, but with JS code.

@rzr moving iotivity-node to 1.2.1 requires some work because of the appearance of `OC(Get|Set)PropertyValue` and the phasing out of `OCSetDeviceInfo` and `OCSetPlatformInfo`. I have to expose these APIs as property accessors on the JS side, because that's what makes the most sense. The JS spec doesn't even allow this information to be modified, but contains a clause that such modification may be possible "in the future". Well, with iotivity, the [future is now](https://www.youtube.com/watch?v=x94CtcReukY) :)

@wind-rider that is definitely a desirable goal. I did want during the pre-publish step to go through a transpilation process in order to further reduce installed code size while increasing code readability and maintainability.

Another question to everybody: Would you like me to make another 1.2.0 release based off the work on [dev](https://github.com/otcshare/iotivity-node/compare/master...gabrielschulhof:dev~1) and maybe a fix to #126, or should I simply keep going towards 1.2.1?

**Comment by zolkis** [comment]
AFAIK OCF onboarding/provisioning happens via a dedicated secure connection. I'd be reluctant  providing provisioning with the same API object that exposes OCF client/server functionality. They need different security policies. 

So at best we'd have a separate API for provisioning, but do we have a use case for doing that from JS? It's usually done with a Provisioning Tool - which can be written in JS as well - but I expect that would be a different project altogether. IMHO provisioning should be a separate repo from iotivity.

Apart from that, we could support security=1 without affecting the OCF JS API, but then implementations need to encapsulate provisioning, or throw an error.

**Comment by wind-rider** [comment]
Is there any news on this topic?
Thoughts on typescript? Lodash removal? Move to iotivity 1.3? security? Code style?

**Comment by gabrielschulhof** [comment]
@wind-rider we released iotivity-node@1.2.1-1 recently. I'm working on 1.3.0, which has security enabled by default. Currently I'm figuring out how to make security work (again), because my preamble-based approach doesn't seem to be working anymore. OTOH, it looks like iotivity has fixed unowned device discovery and ownership transfer, so I'm hoping that I can run the test suite such that the client obtains access to the server using the ownership transfer mechanism for the purposes of performing the test.

I have also replaced lodash with dependencies on those parts of lodash which are actually used, thereby saving like 4 MB.

**Comment by rzr** [comment]
yea security in 1.3.0 might not be fully supported (actually I am trying to figure out why most examples are not working with cbor files)...

Note, I can help updating meta-oic to 1.3.0 once 1.2.1 land in meta-iot-web:
https://github.com/ostroproject/meta-iot-web/pull/41

**Comment by gabrielschulhof** [comment]
@rzr So far, whenever I ran in SECURED=1 mode I had a preamble that created a security configuration file using `json2cbor` for both halves of the test (client *and* server) so that the client had full access to the resources on the server.

I would like to stop using `json2cbor` and use `OCDiscoverUnownedDevices()` and `OCDoOwnershipTransfer()` instead to make the tests work.

That is, for each test, I would like to perform the following preamble:
1. The client discovers all unowned devices.
2. The client assumes ownership of all the discovered unowned devices.
    I'm assuming this will give the client full access to the server with which it's supposed to interact as part of the test, and I'm assuming that if the test server is not among the unowned devices that are discovered then the client already has ownership over the test server because the test has run at least once before.
3. The test proceeds just as it did before SECURED=1.

**Comment by gabrielschulhof** [comment]
FWIW I think we're moving along now with 1.3.0 and all its open issues. I'll close this issue.

**Comment by wind-rider** [comment]
I think the points about coding style and optionally typescript are still there - what do you think about that?
