### ISSUE TITLE
A simple example with API functions

### ISSUE THREAD

**Issue by DimitrisLinaritis** [otcshare/iotivity-node#133]
Hello i am an undergraduate student and i am having a project about iotivity-node. Can you write a simple example with client and server how to discover and retrieve a resource (i am using API's functions like retrieve,register,etc). Thank you!

**Comment by thiagogcm** [comment]
I believe what you're asking is already on the samples
https://github.com/otcshare/iotivity-node/blob/master/js/high-level-client-example.js
https://github.com/otcshare/iotivity-node/blob/master/js/high-level-server-example.js

**Comment by gabrielschulhof** [comment]
@thiagogcm thanks for the pointers!

@DimitrisLinaritis hopefully this information was useful. If you run into any problems with iotivity-node, please file another issue!
