### ISSUE TITLE
Retrieve all the possible values

### ISSUE THREAD

**Issue by VasilisCh** [otcshare/iotivity-node#134]
I am an undergraduate student and i am working on a project about a perfect interactive/smart house. I need to make a retrieve request and take all the possible values/restrictions from a resource's properties. 

e.g. i have an air-condition for a resource and it's property is an enum for state: { 'on', 'off', 'sleep' }. Making a retrieve request gives me a string. How can i get all its' possible values?

Thanks! :)

**Comment by wind-rider** [comment]
I think that is what "introspection" is for - to inspect a device's capabilities and schema. I'm not sure if and how that works with iotivity-node though.

**Comment by gabrielschulhof** [comment]
@VasilisCh device properties follow a [schema](http://www.oneiota.org/documents?filter%5Bmedia_type%5D=application%2Framl%2Byaml). Some properties are specified as "enum", in which case the schema lists all possible values.

**Comment by jvalsam** [comment]
Hello, I have the same problem.
I participate in a project that we have to automatic generate respective GUI application in which
the user can control (i.e. change values of the properties) of the connected smart devices.
For example, in case of the air-condition enum state { 'on', 'off', 'sleep' }, we would like to generate
e.g. 
<select>
  <option value="on">ON</option>
  <option value="off">OFF</option>
  <option value="sleep">SLEEP</option>
</select>
In addition, restrictions of numbers (e.g. possible values temperature of air-condition) etc.

Is there any way to retrieve possible values, restrictions etc.?

Thank you in advance! :)

**Comment by gabrielschulhof** [comment]
@VasilisCh if you have any other concerns about the way iotivity-node works, please file another issue!
