### ISSUE TITLE
Errors during iotivity-node installation. How to install iotivity-node properly?

### ISSUE THREAD

**Issue by bart84** [otcshare/iotivity-node#143]
Hello there!

I will be very specific and will divide my question into points.

I am running a Ubuntu 14.04 LTS machine with node.js on board

**1. What I want to achieve in overall:**

I want to install the iotivity-node npm package on my local computer

**2. What is not working:**

During the installation I get the following logs and errors:

> iotivity-node@1.2.1-1 install /usr/local/lib/node_modules/iotivity-node node-gyp rebuild
> 
> make: Entering directory `/usr/local/lib/node_modules/iotivity-node/build' ACTION Building CSDK iotivity-installed Cloning into '/usr/local/lib/node_modules/iotivity-node/iotivity-native'... remote: Counting objects: 3825, done remote: Finding sources: 100% (3825/3825) remote: Total 3825 (delta 281), reused 1993 (delta 281) Receiving objects: 100% (3825/3825), 13.87 MiB | 365.00 KiB/s, done. Resolving deltas: 100% (281/281), done. Checking connectivity... done. Note: checking out '0c90ca6ffcbb6a2c56c977ec11bebb7b1d14053b'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:
> 
> git checkout -b new_branch_name
> 
> Cloning into '/usr/local/lib/node_modules/iotivity-node/iotivity-native/extlibs/tinycbor/tinycbor'... error: RPC failed; result=35, HTTP code = 0 fatal: The remote end hung up unexpectedly make: *** [iotivity-installed] Error 128 make: Leaving directory /usr/local/lib/node_modules/iotivity-node/build' gyp ERR!
>   build error  gyp ERR! stack Error:make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23) gyp ERR! stack at emitTwo (events.js:106:13) gyp ERR! stack at ChildProcess.emit (events.js:191:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12) gyp ERR! System Linux 3.13.0-107-generic gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /usr/local/lib/node_modules/iotivity-node gyp ERR! node -v v6.4.0 gyp ERR! node-gyp -v v3.4.0 gyp ERR! not ok npm ERR! Linux 3.13.0-107-generic npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "iotivity-node" npm ERR! node v6.4.0 npm ERR! npm v3.10.8 npm ERR! code ELIFECYCLE
> 
> npm ERR! iotivity-node@1.2.1-1 install: node-gyp rebuild npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the iotivity-node@1.2.1-1 install script 'node-gyp rebuild'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the iotivity-node package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! node-gyp rebuild npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs iotivity-node npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm owner ls iotivity-node npm ERR! There is likely additional logging output above.

**3. Have you run across this issue while installing iotivity-node and if yes how you have resolved it? Thank you in advance for your answers.**

**Comment by gabrielschulhof** [comment]
@bart84 looks like there was an error cloning the tinycbor git repo. You should simply try again. Let me know if it keeps failing!

**Comment by gabrielschulhof** [comment]
@bart84 looks like things have cleared up. If you're still running into errors, please open another issue!
