### ISSUE TITLE
Discovered resources,findResources()

### ISSUE THREAD

**Issue by DimitrisLinaritis** [otcshare/iotivity-node#144]
Can i know how many resources have been discovered using findResources() or another function??

**Comment by gabrielschulhof** [comment]
The discovery process is open-ended, so you don't know when it's going to finish. Thus, you can count how many resources have been discovered *so far* by attaching a listener to the "resourcefound" event on `device.client`. There's no guarantee, however, that a resource won't appear after some time.

**Comment by gabrielschulhof** [comment]
Hopefully this answers your question. If you find anything amiss, please open another issue.
