### ISSUE TITLE
security: persistent storage folder != sha256sum of the main script path

### ISSUE THREAD

**Issue by ttzeng** [otcshare/iotivity-node#146]
The setup instruction of the [SECURITY.md](https://github.com/otcshare/iotivity-node/blob/master/SECURITY.md#setting-up-security):

> The sha256sum of the absolute path of the main script which was used to launch the node process is computed.

However, the actual path used does not match the output of sha256sum in my case:
```$ sha256sum /home/tzeng/iotivity-node/tools/binarySwitch.js```
```0b43e83c6adbafba126e1dfe7e26609223bf8889a1babe8c4c626954108230c5  /home/tzeng/iotivity-node/tools/binarySwitch.js```

The new folder was created after launching the script:
```tzeng@ttzeng-mobl3:~/.iotivity-node/ $ ls```
```35d328aeeb70f0110f6bd5d42d2372807b090eba4316fba29d29ec3cdaa76ab0```

**Comment by gabrielschulhof** [comment]
It's the sha256sum of the string representing the absolute path of the
script, not the sha256sum of the contents of the file at that path. I
usually do

echo -n '/home/nix/iot/iotivitiy-node/js/high-level-server-example.js' |
sha256sum

If you're on Windows, I'm not sure what capitalization it uses for the
directory or the file name.

The other way to find out what the directory is is exactly what you did:

$ rm -rf ~/.iotivity-node
$ node /home/nix/iot/iotivitiy-node/js/high-level-server-example.js
^C
$ ls -l ~/.iotivity-node

**Comment by ttzeng** [comment]
@gabrielschulhof sorry I misinterpreted what it means. With the given instruction, it's crystal clear now.

**Comment by gabrielschulhof** [comment]
@ttzeng NP. I should have made the documentation clearer, and now I have, thanks to your bug report :)
