### ISSUE TITLE
Missing 1.3.0 tag?

### ISSUE THREAD

**Issue by gvancuts** [otcshare/iotivity-node#151]
There are a number of tags in this repo which, I guess, map to the versions of `iotivity-node` released on npmjs.org. There is however no 1.3.0-1 (nor 1.3.0-0 for that matter). Is it a miss?

**Comment by gabrielschulhof** [comment]
Oops! Fixed now :)

**Comment by gabrielschulhof** [comment]
The npm-published version does indeed always coincide with the git tag.

**Comment by gvancuts** [comment]
Thanks @gabrielschulhof !
