### ISSUE TITLE
why removed object in payload.values?

### ISSUE THREAD

**Issue by karavolt** [otcshare/iotivity-node#159]
hi, 

i'm trying to send response for get method.
but client can't get data property in payload.values.

ex) 
server send response like this: 
`payload = { 
     type: iotivity.OCPayloadType.PAYLOAD_TYPE_REPRESENTATION,
     values: { 
        serial: 'uuid',
        data: {
          text: 'hello',
          id: 1
        }
     }
}
`
then client get response
`payload: {
  type:4,
  values: {
    serial: 'uuid',
    data: null
  }
}
`
is this spec problem? or node version problem?
client using 7.10.1 version, server using 6.11.4 version.

**Comment by gabrielschulhof** [comment]
The payload needs to look like this:
```JS
{
  type: iotivity.OCPayloadType.PAYLOAD_TYPE_REPRESENTATION,
  values: {
    serial: 'uuid',
    data: {
      type: iotivity.OCPayloadType.PAYLOAD_TYPE_REPRESENTATION,
      values: {
        text: 'hello',
        id: 1
      }
    }
  }
}
```

**Comment by gabrielschulhof** [comment]
This iotivity-node [test](https://github.com/otcshare/iotivity-node/blob/master/tests/tests/Complex%20Payload/server.js#L77-L89) gives you an example of a payload that has object-valued properties.
