### ISSUE TITLE
Invalid representation payload while sending property of object array

### ISSUE THREAD

**Issue by ttzeng** [otcshare/iotivity-node#160]
With the current master branch (commit: c3ecd6e9b50bd4139d9178636df94525199ba24a), resource property of array type causing `repPayloadToObject: Invalid representation payload` error at the receiving end.

For example, the [rgb_led.js](https://github.com/intel/SmartHome-Demo/blob/master/ocf-servers/js-servers/rgb_led.js) server hosts a resource with properties `rgbValue` and `range`, which are array of integers, to represent a [RGB color resource](https://oneiota.org/revisions/1797), but sending that property causes errors at the receiving end. The `errorHandler` of the receiver(client) indicates it's `repPayloadToObject: Invalid representation payload`error.

> [Server]
> function getProperties() {
>     var properties = {
>         ...
>         rgbValue: [ 0, 0, 0],
>         ...
>     }
>     function retrieveHandler(request) {
>         res.properties =  getProperties();
>         request.respond(res);
>     }
> [Client]
> ...
> function errorHandler(error) {
>     debuglog('Server responded with error', error.message);
> }
> client.on('error', errorHandler);
> client.on('resourceFound', function(res) {
>     ...
>     res.on('error', errorHandler);
> });

**Comment by ttzeng** [comment]
@gabrielschulhof thank you for looking into this, I verified the code at [f4a83a1a](https://github.com/otcshare/iotivity-node/commit/f4a83a1ac18bc688aaa085e6dde7da797047f365), both coaps and value array properties are function well. Would you like to push the `1.3.0-3` label to this commit as the last before bumping to 1.3.1?

**Comment by gabrielschulhof** [comment]
Thanks for reminding me!

I now pushed the tag, and I also released the first version to support
coaps. It's based on iotivity@1.3.1-RC6. Unfortunately I was unable to get
it to work on Windows and OSX, but at least on Linux coaps access and
server provisioning using the provided sample provisioningclient works.
