### ISSUE TITLE
Parameter '--suites="!API Retrieve Secure Resource"' doesn't work in appveyor.yml on windows10 or windows8.1

### ISSUE THREAD

**Issue by xiaoyu3x** [otcshare/iotivity-node#169]
I got the same result when executing 'grunt testsuite' with commit [4835fb6](https://github.com/otcshare/iotivity-node/commit/4835fb61fe845cc1d3034e08940a759f7175c12f) and [257dde7](https://github.com/otcshare/iotivity-node/commit/257dde777416e0456370b10eaa33b9d4ed0e7d9a).
JS "!API Retrieve Secure Resource" still failed.
![default](https://user-images.githubusercontent.com/17694094/34936182-3d45ef88-f995-11e7-8ed8-d458ded32174.PNG)

**Comment by gabrielschulhof** [comment]
If you run 
```
grunt testsuite
```
It will run all the tests. If you run
```
grunt testsuite --suites="!API Retrieve Secure Resource"
```
it will run all the tests except "API Retrieve Secure Resource".

In the above screenshot, you ran `grunt testsuite` - thus, it ran "API Retrieve Secure Resource" as well.

IOW what you saw is the expected result.

The reason I added the ability to specify "!<testlist>" is to be able to [change appveyor.yml](https://github.com/otcshare/iotivity-node/commit/257dde777416e0456370b10eaa33b9d4ed0e7d9a#diff-180360612c6b8c4ed830919bbb4dd459R32) to not run "API Retrieve Secure Resource".

It works on appveyor: https://ci.appveyor.com/project/gabrielschulhof/iotivity-node/build/1.0.293/job/ikejqqo6y0u6dwcs#L753

**Comment by xiaoyu3x** [comment]
Thanks, @gabrielschulhof 
It is successful that JS "API Retrieve Secure Resource" is skipped with grunt testsuite --suites="!API Retrieve Secure Resource" on windows10 with node_version 4.11.0.
About test method of testsuite  on windows platform, I think its expression isn't clear in README.md.
To this problem, I offer PR #170 . Please help me to merge it if you think it is OK.
