### ISSUE TITLE
client.updateResource(USVString resourceId, OicResourceInit resource) should send the update event

### ISSUE THREAD

**Issue by nagineni** [otcshare/iotivity-node#26]
client.updateResource(USVString resourceId, OicResourceInit resource) should send the 'update' event, instead of 'create'.

https://github.com/otcshare/iotivity-node/blob/master/lib/OicClient.js#L283
https://github.com/otcshare/iotivity-node/blob/master/lib/OicServer.js#L157

**Comment by gabrielschulhof** [comment]
This is fixed since cbe691c4d1031d559956d6afb24a94d44a0d737d and tested since a1b7bea05bd3d15eb9cd62195911ba9eb2661822

**Comment by nagineni** [comment]
@gabrielschulhof, thanks for fix.
