### ISSUE TITLE
Adding an empty server to the network prevents discovery of resources on other servers

### ISSUE THREAD

**Issue by gabrielschulhof** [otcshare/iotivity-node#34]
1. Write a client that does a discovery every two seconds:
    ```JS
    var device = require( "./index" )();
    
    function throwError( error ) {
    	throw error;
    }
    
    function resourceFound( resource ) {
    	console.log( "resourceFound: " + JSON.stringify( resource, null, 4 ) );
    }
    
    function repeatedDiscovery() {
    	device.client.addEventListener( "resourcefound", resourceFound );
    	setInterval( function() {
    		console.log( "Calling findResources()" );
    		device.client.findResources().catch( throwError );
    	}, 2000 );
    }
    
    device.configure( {
    	role: "client",
    	connectionMode: "acked"
    } ).then( repeatedDiscovery, throwError );
    ```
2. Run ```node js/server.discoverable.js``` and observe as the client repeatedly discovers the server
3. Write an empty server and run it:
    ```JS
    var device = require( "./index" )();
    
    device.configure( {
    	role: "server",
    	connectionMode: "acked"
    } );
    ```
4. Watch the output of the client

**Expected:** The client keeps discovering the one resource presented by ```js/server.discoverable.js```

**Actual:** No resources are discovered until you kill the empty server

**Comment by gabrielschulhof** [comment]
@poussa @nagineni @zolkis @siovene this is fixed in iotivity master.

**Comment by gabrielschulhof** [comment]
I've [asked iotivity-dev](http://lists.iotivity.org/pipermail/iotivity-dev/2015-November/003088.html) whether it might be possible to get this fix out in a 1.0.x release.

**Comment by gabrielschulhof** [comment]
OK, so I realized that I wasn't handling the result value from the iotivity OCDoResult response correctly. @nagineni could you please verify that this fixes the discovery breakage for your use case?

**Comment by gabrielschulhof** [comment]
... and by "this", I mean branch 34-handle-no-resource-response :)

**Comment by nagineni** [comment]
@gabrielschulhof, thanks for the fix. I quickly checked and the discovery works fine with this change.
