### ISSUE TITLE
Unable to test with native server.

### ISSUE THREAD

**Issue by as2902b** [otcshare/iotivity-node#44]
No resources are reported when testing with version 1.0.1 of iotivity.
OCF Server version 1.0.1
Nodejs iotivity client built with OCTBSTACK LIBS AND CFLAGS set to same version.
The client is able to discover the server
BUT, no resources are reported.

What do I do to make this work?

**Comment by gabrielschulhof** [comment]
Hey!

I have created https://www.youtube.com/watch?v=95VTB_qgYfw to show you how to set things up from scratch on a Fedora 23 Cloud image.

If you use a different environment, please let me know what version of node you're using, what OS, etc., and I can try that environment instead.

**Comment by as2902b** [comment]
I cannot thank you enough for this detailed video.
I got my entire demo setup and devices working with this version of iotivity and iotivity-node.
Thank you once again.
