### ISSUE TITLE
signed/unsigned char

### ISSUE THREAD

**Issue by pohly** [otcshare/iotivity-node#49]
When char == signed char, conversion to and from uint_8 fails in some
places. Started to happen recently in Ostro OS, perhaps because of a
compiler update. Exact root cause unknown, logs for example here:
https://ostroproject.org/jenkins/job/build_intel-corei7-64/1470/console

A patch fixing the problem is here:
https://github.com/pohly/iotivity-node/commit/abe2ce9ce95c002197cf660b5eb856988dfc9b16

Beware, the commit is against the version currently used in Ostro OS and
also might not be the best solution to the problem (see commit
message). Please rebase and/or fix as you see fit.

I would have done a PR, but that failed because of the rebase master branch (issue #48).

**Comment by gabrielschulhof** [comment]
@nagineni and I believe that you're seeing this issue in Ostro because the version of iotivity that ships with it has been bumped to 1.1.0, whereas the version of iotivity-node has remained at 1.0.1-x. This is fixed in iotivity-node 1.1.0-x.
