### ISSUE TITLE
Failed to get properties of the interface OicDevice

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#52]
Accord to the spec, all properties of the interface OicDevice should exist and can get the default value by following command:
```
var oic = require('iotivity-node')('client');
var oicDevice = oic.device;
console.log(oicDevice.uuid);
console.log(oicDevice.url);
console.log(oicDevice.name);
console.log(oicDevice.dataModels);
console.log(oicDevice.coreSpecVersion);
console.log(oicDevice.role);
```
Actually, the properties `uuid` and `role` exist in the interface `OicDevice` and the other properties are undefined.
A part of  `OicPlatform` properties are defined that is similar as  `OicDevice`.

**Comment by gabrielschulhof** [comment]
iotivity only supports the following attributes for device :
* ```uuid``` - this is readonly
* ```name``` - this is read-write
* ```types``` - this is not part of the spec, and I'm not sure that this corresponds to the ```dataModels``` property. I could map it like that, but I'm not sure I should. Currently I always set it to an empty array.

@zolkis perhaps some of these things need to be marked as optional.
So, @wanghongjuan ```oicDevice.name``` will not be undefined if you first set it. Also, you must set the whole ```info``` at a time, not just the property:
```JS
oicDevice.info = _.extend( oicDevice.info, { name: "my-device" } );
```

**Comment by wanghongjuan** [comment]
If I must set the whole `info` every time, the specification should specify about the usage of  the attributes, is it right? How about another attribute `oicDevice.role`? Why `oicDevice.role` is exist whether iotivity not support it?

**Comment by gabrielschulhof** [comment]
iotivity does support oicDevice.role. In fact, the role determines whether the stack starts as a client or as a server. The constructor accepts this parameter and stores it in the device info structure's ```role``` property.

**Comment by wanghongjuan** [comment]
OK, I think the specification should specify it. Thanks for comments.

**Comment by nagineni** [comment]
As per the spec, OicDevice and OicPlatform information is exposed on the /oic/d (device) and oic/p (pltaform) resources. So, you probably need to discover for the /oic/d and oic/p first and get the properties of the device and platform for the validation.

Also note that most of the properties must be set first when the device is created.

```
oic = require( "iotivity-node" )( "server" ),
_ = require( "lodash" );

oic.device = _.extend( oic.device, {
    name: "api-server-example"
} );

oic.platform = _.extend( oic.platform, {
    manufacturerName: "xyz",
    manufactureDate: new Date( "Wed Jul 13 10:04:17 (EET) 2016" ),
    platformVersion: "1.0.1",
    firmwareVersion: "0.0.1",
    supportUrl: "http://example.com/"
} );
```

**Comment by wanghongjuan** [comment]
@nagineni there have some properties of the interface OicDevice are undefined, such as `url` and `dataModels`, although I have been set them first when the device is created. About the property `role`, it will be undefined if get it by method `getDeviceInfo()`.
