### ISSUE TITLE
The page is not found when click "Core Specification" link in the spec

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#54]
As the spec that the link in the content of `Abstract` should be available . 
`This document presents a JavaScript API for OIC Core Specification, based on the Soletta C API.`
The link for `OIC` and `Soletta C API` can be open, but get `Page Not Found` when open the `Core Specification`.

**Comment by gabrielschulhof** [comment]
The spec now resides in the soletta repo.
