### ISSUE TITLE
node-gyp rebuild fails against local iotivity build

### ISSUE THREAD

**Issue by jspark311** [otcshare/iotivity-node#55]
Hello,

First of all, thanks for the work putting this package together. I'm trying to build against my local development branch of iotivity. I followed the instructions in the README, read the issues, and I think I'm seeing something unreported.

```
#node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/iotivity-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/iotivity-node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/root/iotivity-node/build'
  TOUCH Release/obj.target/csdk.stamp
  ACTION Generating constants generated/constants.cc
  TOUCH Release/obj.target/generateconstants.stamp
  ACTION Generating enums generated/enums.cc
  TOUCH Release/obj.target/generateenums.stamp
  CXX(target) Release/obj.target/iotivity/generated/constants.o
../generated/constants.cc:100:17: warning: extra tokens at end of #ifdef directive
 #ifdef OC_UNUSED(x)
                 ^
In file included from ../generated/constants.cc:20:0:
../generated/constants.cc: In function 'void InitConstants(v8::Handle<v8::Object>)':
../generated/constants.cc:101:42: error: 'x' was not declared in this scope
   SET_CONSTANT_NUMBER(exports, OC_UNUSED(x));
                                          ^
/root/iotivity-node/src/enums.h:26:27: note: in definition of macro 'SET_CONSTANT_NUMBER'
                 Nan::New((name)),                                \
                           ^
../generated/constants.cc:101:32: note: in expansion of macro 'OC_UNUSED'
   SET_CONSTANT_NUMBER(exports, OC_UNUSED(x));
                                ^
make: *** [Release/obj.target/iotivity/generated/constants.o] Error 1
iotivity.target.mk:127: recipe for target 'Release/obj.target/iotivity/generated/constants.o' failed
make: Leaving directory '/root/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```
Here is a docker file to reproduce my environment. I have the npm install step commented out in the Buildscript so that it's easy to intervene and test on a fresh pull from your repo. I have tried both the install.sh method, as well as the manual env variable assignment method.
https://github.com/jspark311/IoTivityNodeSecDocker

I don't think this is actually a problem with iotivity-node. But I'm not sure. 
If this *is* iotivity's fault, it was introduced April 11:
https://github.com/iotivity/iotivity/blob/master/resource/csdk/stack/include/octypes.h#L348

https://github.com/iotivity/iotivity/commit/c9a7bb4fbf2656133578cfd1d757d4cb8a91fb63

Have you seen any problems with this macro? Am I doing it wrong? Any guidance would be appreciated.

**Comment by jspark311** [comment]
FWIW, I tried prepending...
#include <octypes.h>
...to the generated file and re-running. Just to make sure it wasn't a case of the macro not being defined. Failed exactly the same way.

The IoTivity SDK builds. So the only thing making me think it might be this package at fault is the fact that OC_UNUSED is the only macro in octypes.h that takes an argument, and the possibility of generate-constants.sh scraping a file and then using the macro definition blindly (in a place where "x" is not defined).

**Comment by gabrielschulhof** [comment]
iotivity-node is designed to work with iotivity 1.1.0. Making it work with the master branch or anything later than 1.1.0 requires some porting effort. In this case, I believe you need to tweak [generate-constants.sh](https://github.com/otcshare/iotivity-node/blob/master/generate-constants.sh) to recognize ```OC_UNUSED``` as a macro rather than a constant. That will cause it to avoid adding it to the collection of ```#define```-ed constants it adds to main.cc.

Keeping up with iotivity is part of my goal. I'll try to have a look at this as soon as I can.

**Comment by jspark311** [comment]
Yes.... That's how I ended up "fixing" it. Stripping out the macro'd expression in the generated constants.cc masks the problem.
I will close this issue. As far as I can tell, the root-cause is sloppiness in IoTivity (expression treated as macro).
Thanks. :-)

**Comment by gabrielschulhof** [comment]
Actually, the root cause is in iotivity-node. iotivity introduced the macro ```OC_UNUSED()``` quite legitimately, but the parser in iotivity-node was misidentifying it as a constant and thus attempting to expose it to Javascript.

I'll re-open the issue until the fix actually lands on master.

Thanks for reporting!
