### ISSUE TITLE
Build failure caused by tinycbor

### ISSUE THREAD

**Issue by HanYangZhao** [otcshare/iotivity-node#63]
During installation , I get 

`out/linux/x86_64/release/resource/csdk/stack/src/ocpayloadparse.os: In function `OCParseStringLL':
ocpayloadparse.c:(.text+0xaf): undefined reference to `_cbor_value_dup_string'
out/linux/x86_64/release/resource/csdk/stack/src/ocpayloadparse.os: In function `OCParseSingleRepPayload':
ocpayloadparse.c:(.text+0x3d1): undefined reference to `_cbor_value_dup_string'
ocpayloadparse.c:(.text+0x557): undefined reference to `_cbor_value_dup_string'
ocpayloadparse.c:(.text+0x59c): undefined reference to `_cbor_value_dup_string'
out/linux/x86_64/release/resource/csdk/stack/src/ocpayloadparse.os: In function `OCParseArrayFillArray':
ocpayloadparse.c:(.text+0xa58): undefined reference to `_cbor_value_dup_string'
out/linux/x86_64/release/resource/csdk/stack/src/ocpayloadparse.os:ocpayloadparse.c:(.text+0xa9e): more undefined references to `_cbor_value_dup_stri
ng' follow`

Which causes scons to fail. I think the problem is due to this https://github.com/01org/tinycbor/commit/4ce56694ed3bd1f1ce36f7fb50f4c79f68726dbd commit. 

Any ideas? Thanks

**Comment by nagineni** [comment]
Here is the patch to checkout the working revision of tinycbor - https://github.com/otcshare/iotivity-node/pull/62
