### ISSUE TITLE
Update resourse event

### ISSUE THREAD

**Issue by KunalSaini** [otcshare/iotivity-node#74]
Hi, I am trying to update a resource however getting following error .
```Error: update: OCDoResource response failed```
following is my server / resource definition
```Javascript
var setpoint = 0;
device.register({
    id: { path: "/a/setpoint" },
    resourceTypes: [ "oic.r.switch.binary" ],
    interfaces: [ "oic.if.baseline" ],
    discoverable: true,
    observable: true,
    properties: { on: false }
  }).then((res) => {
    setpoint = res;
    device.addEventListener('observerequest', log);
    device.addEventListener('retrieverequest', log);
    device.addEventListener('updaterequest', log);
    console.log('setpoint register OK');
  }).catch(error => console.log(`error registering setpoint - ${error}`));

  function log(request) {
    console.log("setpoint: request " + request.type);
    request.sendResponse(setpoint);
  }
```
And following is the client 

```Javascript
const client = require( "iotivity-node" )( "client" );
client.addEventListener( "resourcefound", function( event ) {
	if(event.resource.id.path === '/a/setpoint') {
		client.update({id: event.resource.id, setpoint: 10 })
		.then(() => console.log('changed setpoint'))
		.catch((error) => console.log(`unable to change setpoint - ${error}`));
	}
} );
client.findResources();
```

**Comment by mythi** [comment]
@KunalSaini please specify the ostro-os image you are using and the iotivity* versions.

**Comment by KunalSaini** [comment]
@mythi I am on the latest Ostro Os build 497 "ostro-image-swupd-all-intel-quark.dsk.xz" image. 
The Iotivity-node version is 1.1.0-4. I am not sure about the underlying iotivity version , however i think its 1.1.1

**Comment by nagineni** [comment]
@KunalSaini I don't see any issue running sample code with the iotivity-node v1.1.0-4.

Here is the client & server outptut:

```
# node client.js 
changed setpoint

# node server.js 
setpoint register OK
setpoint: request updaterequest
```

**Comment by nagineni** [comment]
BTW, latest Ostro has iotivity v1.1.0. Update for v1.1.1 is in pending queue.

**Comment by KunalSaini** [comment]
thanks @nagineni I guess I was running the client on iotivity-node 1.1.1-3 and server on 1.1.0-4 as I cant get the older version to install properly on my laptop. Hoping the ostro os will soon incorporate the latest version. meanwhile i also figured that passing the whole resource in ```client.update``` call resolves the issue for me.

**Comment by gabrielschulhof** [comment]
Since this issue seems to be fixed, I will close it.
