### ISSUE TITLE
[REG] Iotivity-node doesn't work due to some changes of firewall in latest Ostro

### ISSUE THREAD

**Issue by wanghongjuan** [otcshare/iotivity-node#75]
Some asserts are failed due to the firewall setting, list all failed tests:
```
API Complex Payload
API Create Delete
API Device ID Persistence.js
API Device Information
API Device Rediscovery.js
API Discovery
API Error Propagation
API Observation
API Presence
API Query Parameters
API Retrieve
Complex Payload
Device Entity Handler
Discovery
Get Request
Multiple Observers
Observation
Presence
```

#### Reproduce Steps:
1. Enter the test device and get the source code by command:
```git clone https://github.com/otcshare/iotivity-node.git```
2. Copy some necessary files to "/usr/lib/node_modules/iotivity-node"
File list:` Gruntfiles.js, .jscsrc, grunt-build and tests`
3. Install the node modules that defined in file "package.json" and "grunt-cli"
``` cd /usr/lib/node_modules/iotivity-node; npm install; npm install grunt-cli```
4. Run tests via below command:
``` ./node_modules/grunt-cli/bin/grunt test```, some tests are failed and show timeout. 
5. Try to run a single tests with below commands:
```sh
$: node tests/tests/API\ Complex\ Payload/server.js 
{"assertionCount":3}
{"ready":true}
$: node tests/tests/API\ Complex\ Payload/client.js (Open a new terminal and run it)
{"assertionCount":1}
(Then the script will hang on this, no error message)
```

#### Test Environment: 
Galileo with [build#497].

[build#497]: https://download.ostroproject.org/builds/ostro-os/2016-09-07_08-11-14-build-497/images/intel-quark/

**Comment by gabrielschulhof** [comment]
When you run the tests by hand, you should use ```uuidgen``` to give them both a UUID:
```
$ uuidgen
7b8b5795-bf6a-4551-becd-c98247d70d0a
$ node tests/tests/API\ Complex\ Payload/server.js 7b8b5795-bf6a-4551-becd-c98247d70d0a
{"assertionCount":3}
{"ready":true}
...
new terminal
...
$ node tests/tests/API\ Complex\ Payload/client.js 7b8b5795-bf6a-4551-becd-c98247d70d0a
...
```
That's because the server usually creates the resource ```/a/<uuid>``` and the client finds the server by looking for resources of that name.

**Comment by wanghongjuan** [comment]
Yes, I forgot it. Thanks for your reminder. I tried to re-run this test after added the uuid, this issue is still exists. @nagineni tell me that create holes to the firewall like in the this [commit](https://github.com/ostroproject/meta-iotqa/pull/194/commits/485a83823763539e82037cbec3a8d13f061cfd5b)  to set the firewall in Ostro and it works, the tests are passed. So close this issue.
