### ISSUE TITLE
Found new crash on x86_64

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#80]
Thread 1 "node" received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x0000000000857754 in v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) ()
#2  0x00007fffe65f3e59 in js_OCPayload(OCPayload*) ()
   from /home/dev/demo/iotivity/wsi/iotivity-node/build/Release/iotivity.node
#3  0x00007fffe65eb039 in js_OCClientResponse(OCClientResponse*) ()
   from /home/dev/demo/iotivity/wsi/iotivity-node/build/Release/iotivity.node
#4  0x00007fffe65e0842 in defaultOCClientResponseHandler(void*, void*, OCClientResponse*) ()
   from /home/dev/demo/iotivity/wsi/iotivity-node/build/Release/iotivity.node
#5  0x00007fffe639acb4 in OCHandleResponse ()
   from /home/dev/demo/iotivity/out/linux/x86_64/release/liboctbstack.so
#6  0x00007fffe5f5ed0b in CAHandleRequestResponseCallbacks ()
   from /home/dev/demo/iotivity/out/linux/x86_64/release/libconnectivity_abstraction.so
#7  0x00007fffe5f5de2e in CAHandleRequestResponse ()
   from /home/dev/demo/iotivity/out/linux/x86_64/release/libconnectivity_abstraction.so
#8  0x00007fffe639bcc3 in OCProcess ()
   from /home/dev/demo/iotivity/out/linux/x86_64/release/liboctbstack.so
#9  0x00007fffe65e640f in bind_OCProcess(Nan::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/dev/demo/iotivity/wsi/iotivity-node/build/Release/iotivity.node
#10 0x00007fffe65d9825 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) () from /home/dev/demo/iotivity/wsi/iotivity-node/build/Release/iotivity.node
#11 0x0000000000870312 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#12 0x000000000089a301 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>&) ()
#13 0x000000000089a75e in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
#14 0x00000e27265068fb in ?? ()
#15 0x00000e2726506841 in ?? ()
#16 0x00007fffffffd3b0 in ?? ()
#17 0x00007fffffffd3f8 in ?? ()
#18 0x00000e272694eab3 in ?? ()
#19 0x00001b3734a96ba9 in ?? ()
#20 0x0000121793e450b1 in ?? ()
#21 0x00001b3734a96ba9 in ?? ()
#22 0x0000338423518721 in ?? ()

**Comment by gabrielschulhof** [comment]
@iamsanjeev what version of iotivity-node is this? Also, can you please give the steps for reproducing this issue?

TBH, I suspect that a really old version of iotivity-node (0.9.2-0) is causing this segfault, because since 0.9.2-1, ```js_OCPayload()``` no longer directly creates any v8 strings making impossible the sequence

> ```
#1 0x0000000000857754 in v8::String::NewFromUtf8(v8::Isolate, char const, v8::NewStringType, int) ()
#2 0x00007fffe65f3e59 in js_OCPayload(OCPayload) ()
```

**Comment by iamsanjeev** [comment]
Not a bug. OCTBSTACK_LIBS was set to incorrect folder.
