### ISSUE TITLE
How to use iotivity-node 1.2.0-RC2 in an external project?

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#82]
Trying to use a specific version needs some guidance.

I am currently doing it wrong with varying degrees of results.
Not sure which is the right way to include an external depedency that has to be built manually.

**Comment by gabrielschulhof** [comment]
@iamsanjeev declare it as a dependency in your package.json:

```
...
  "dependencies": {
...
    "iotivity-node": "git+https://github.com/otcshare/iotivity-node#1.2.0",
...
  },
...
```

**Comment by gabrielschulhof** [comment]
It will still listen to ```OCTBSTACK_CFLAGS``` and ```OCTBSTACK_LIBS```.

**Comment by gabrielschulhof** [comment]
It will still listen to ```OCTBSTACK_CFLAGS``` and ```OCTBSTACK_LIBS```.

**Comment by iamsanjeev** [comment]
thank you, I will try this.

At the moment, I have cloned iotivity-node within my JS app and this form of include seems to work.

var device = require( "../../iotivity-node" )( "client" );
