### ISSUE TITLE
changerequest should be emit by POST requests, instead of PUT requests

### ISSUE THREAD

**Issue by ttzeng** [otcshare/iotivity-node#83]
Checked the RAML of resources in http://oneiota.org, most of resource states are set by POST requests, but iotivity-node only emits 'change' on PUT requests [1], which may cause incompatible with other OCF implementations.

[1] https://github.com/otcshare/iotivity-node/blob/master/lib/OicServer.js#L168-L200

**Comment by gvancuts** [comment]
@poussa , can you ask someone to take a look at this?

**Comment by zolkis** [comment]
That is right. We have discussed this last week, here is the essence.

The OCF Core spec says PUT should be used for creating a resource, and POST for update.

The spec allows using POST to create in certain conditions (when the whole resource is provided and the resource already exists, i.e. there is a handler on the server side already). However, it says that creating with POST is not guaranteed: it is up to the server whether it creates the resource or responds with an error.

Now e.g. in HTTP the PUT request is often blocked by firewalls, therefore using POST is better there.

Anyway we should obey the OCF spec: in the implementations let's use PUT for creating and POST for updating.

**Comment by ttzeng** [comment]
Will this impact the REST API server for updating properties for a specific server?
