### ISSUE TITLE
Cant find version 1.2.0 anymore

### ISSUE THREAD

**Issue by iamsanjeev** [otcshare/iotivity-node#91]
Cloning fails and we are unable to find the version in git logs

**Comment by gabrielschulhof** [comment]
I removed the branch. I merged everything into maintenance once all three platforms (Linux, OSX, and Windows) were green.

**Comment by gabrielschulhof** [comment]
@iamsanjeev https://github.com/otcshare/iotivity-node/tree/maintenance
