### ISSUE TITLE
Module ./lib/OicDevice not found while using the latest commit before moving to 1.2.0

### ISSUE THREAD

**Issue by ttzeng** [otcshare/iotivity-node#94]
I wanted to test the iotivity-node with new features without moving to 1.2.0-0 release, so I checked out the [latest commi](https://github.com/otcshare/iotivity-node/tree/53249fcd62e69206d10f94efb04816f3de9b86e2)t before pumping to 1.2.0. iotivity-node was built and packages the distributable tree successfully, but after untar the distributable tree in the Edison board running [standard Yocto image](https://software.intel.com/edison-image/latest), the OCF servers can not be run, and I got below error, it looks like the module './lib/OicDevice' is missing, it also does not exist in the build tree. DId I miss anything?  Thanks.

root@edison:~/node-examples/iotivity-node# node led.js 
module.js:327
    throw err;
    ^

Error: Cannot find module './lib/OicDevice'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/root/node-examples/iotivity-node/node_modules/iotivity-node/inde)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@edison:~/node-examples/iotivity-node#

**Comment by qiuzhong** [comment]
Hi, @ttzeng , from the error log, I think the node didn't load correct version of iotivity-node. So far as I know, from iotivity-node 1.2.0, there is no lib/OicDevice.js any more. I am afraid the iotivity-node version the node tried loading on your Edison system is still 1.1.x

When node tries to <code>require('iovitity-node')</code>, it actually loads the **index.js**, which simply loads **lib/Device.js** (<code>module.exports = require( "./lib/Device" );</code>, for iotivity-node 1.2.0)

**Comment by ttzeng** [comment]
The Yocto image does not include iotivity-node by default, the only iotivity-node in the device is the one I built iotivity-node with the latest commit before pumping to 1.2.0. Since my OCF servers are still using 1.1.1 API "require('iotivity-node')('server')"

**Comment by nagineni** [comment]
OicDevice.js has been renamed to Device.js, but the index.js still uses the old filename in the commit you are using. 

You can try making the following change in index. js or use the latest released version that contains this fix already.

`-module.exports = require( "./lib/OicDevice" );`
`+module.exports = require( "./lib/Device" );`

**Comment by ttzeng** [comment]
Thanks Babu.  Now I got below error, and it looks like the code already use 1.2.0 API even I checkout [this commit](https://github.com/otcshare/iotivity-node/tree/53249fcd62e69206d10f94efb04816f3de9b86e2).

root@edison:~/node-examples/iotivity-node# node led.js
/home/root/node-examples/iotivity-node/led.js:2
    device = require('iotivity-node')('server'),
                                     ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/home/root/node-examples/iotivity-node/led.js:2:38)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
root@edison:~/node-examples/iotivity-node#

**Comment by qiuzhong** [comment]
Suggest to checkout [this commit](https://github.com/otcshare/iotivity-node/tree/6cb68eeaaf8e814571ceb27c8359aec32e58575e) if your OCF servers use iotivity-node 1.1.1 API.

**Comment by nagineni** [comment]
@ttzeng Your server (i.e led.js) seems to based on the old iotivity-node implementation.

The iovity-node version you built is based on the latest OCF JS API spec, so the server must be updated to the latest API spec to make it work.

I'm working on updating SmartHome demo OCF servers to the latest JS spec. You can try with the servers in the commit https://github.com/01org/SmartHome-Demo/commit/face8f4a8

**Comment by gabrielschulhof** [comment]
@ttzeng there were some changes to the OCF JS API which means you have to make the corresponding changes to all the applications that use iotivity-node. The tests accompanying the OCF JS API spec are excellent [examples](https://github.com/01org/iot-js-api/tree/ocf-1.1.0/tests) of simple applications that make use of the high-level API.

**Comment by ttzeng** [comment]
Thank you @nagineni @gabrielschulhof ! I tried to run the [rgb_led](https://github.com/01org/SmartHome-Demo/blob/iotivity_1.2.0/ocf-servers/js-servers/rgb_led.js) server in the 'iotivity_1.2.0' branch of the smart home demo, but it looks like something need to be done for the insecure mode (unset 'SECURE' env), otherwise the Promise object is pending after invoking server.enablePresence(), and I got 'UNAUTHORIZED_REQ : Request is not authorized by Resource Server' from the client side.

Do we support only secure mode for now?

**Comment by gabrielschulhof** [comment]
@ttzeng I think so. I certainly don't test without SECURED=1 anymore.

**Comment by nagineni** [comment]
@ttzeng  Servers and cleint apps works in non-secure mode also, if we build and install iotivity without SECURED=1. I tried on my custom Yocto build(iotivity without SECURED=1) and the apps seems to be working fine in non-secure mode.

**Comment by ttzeng** [comment]
My iotivity-node on the server side is installed by "npm install", is it enable secured mode by default?

**Comment by gabrielschulhof** [comment]
@ttzeng yes. By default, 1.2.0-0 builds iotivity internally with `SECURED=1`, unless you specify both `OCTBSTACK_CFLAGS` and `OCTBSTACK_LIBS`.

**Comment by ttzeng** [comment]
Thanks @gabrielschulhof @nagineni for the clarifications, I have no further question, and we could close this now. Thank you~
