### ISSUE TITLE
Install is failed

### ISSUE THREAD

**Issue by micrcx** [otcshare/iotivity-node#95]
michael_k@Dell-55RFD12 ~/iotivity-node-master $ npm install

> iotivity-node@1.2.0-0 install /home/michael_k/iotivity-node-master
> node-gyp rebuild

make: Entering directory `/home/michael_k/iotivity-node-master/build'
  ACTION Building CSDK iotivity-installed

/home/michael_k/iotivity-node-master/build-scripts/build-csdk.js:24
	spawnSync( command, arguments, _.extend( {}, options, {
	^
TypeError: undefined is not a function
    at run (/home/michael_k/iotivity-node-master/build-scripts/build-csdk.js:24:2)
    at Object.<anonymous> (/home/michael_k/iotivity-node-master/build-scripts/build-csdk.js:89:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
make: *** [iotivity-installed] Error 8
make: Leaving directory `/home/michael_k/iotivity-node-master/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/michael_k/iotivity-node-master
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by qiuzhong** [comment]
You node version(v0.10.25) is too low, [<code>child_process.spawnSync</code>](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) was introduced to Node.JS from v0.11.12

**Comment by micrcx** [comment]
Hi,
I've updated Node.js to version 0.12.0. However, the installation is still
failed:
michael_k@Dell-55RFD12 ~ $ cd iotivity-node-master/
michael_k@Dell-55RFD12 ~/iotivity-node-master $ npm install
\
> iotivity-node@1.2.0-0 install /home/michael_k/iotivity-node-master
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/michael_k/iotivity-node-master/build'
  ACTION Building CSDK iotivity-installed
Cloning into '/home/michael_k/iotivity-node-master/iotivity-native'...
remote: Counting objects: 4123, done
remote: Finding sources: 100% (4123/4123)
remote: Total 4123 (delta 297), reused 1855 (delta 297)
Receiving objects: 100% (4123/4123), 14.07 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (297/297), done.
Checking connectivity... done.
Note: checking out '1a2e71f9c470c7cc17157f83deb4488ee83050a4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Cloning into
'/home/michael_k/iotivity-node-master/iotivity-native/extlibs/mbedtls/mbedtls'...
remote: Counting objects: 43568, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 43568 (delta 1), reused 0 (delta 0), pack-reused 43566
Receiving objects: 100% (43568/43568), 19.99 MiB | 933.00 KiB/s, done.
Resolving deltas: 100% (33217/33217), done.
Checking connectivity... done.
Note: checking out 'ad249f509fd62a3bbea7ccd1fef605dbd482a7bd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ad249f5... Fixes all.sh script for filesystem IO test build
Cloning into
'/home/michael_k/iotivity-node-master/iotivity-native/extlibs/tinycbor/tinycbor'...
remote: Counting objects: 967, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 967 (delta 0), reused 0 (delta 0), pack-reused 964
Receiving objects: 100% (967/967), 471.41 KiB | 114.00 KiB/s, done.
Resolving deltas: 100% (575/575), done.
Checking connectivity... done.
Note: checking out '31c7f81d45d115d2007b1c881cbbd3a19618465c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 31c7f81... Makefile: use installation logic compatible with
old make version
scons: Reading SConscript files ...
Reading linux configuration script
Checking for POSIX Thread Support...yes
*** Checking for installation of SQLite 3.8.11.1 (extlib/sqlite3) ***
Download
/home/michael_k/iotivity-node-master/iotivity-native/extlibs/sqlite3/sqlite-amalgamation-3081101.zip
from https://www.sqlite.org/2015/sqlite-amalgamation-3081101.zip
Downloading ...
Download
/home/michael_k/iotivity-node-master/iotivity-native/extlibs/sqlite3/sqlite-amalgamation-3081101.zip
from https://www.sqlite.org/2015/sqlite-amalgamation-3081101.zip complete
Unzipping SQLite amalgamation src...
Unpacking
/home/michael_k/iotivity-node-master/iotivity-native/extlibs/sqlite3/sqlite-amalgamation-3081101.zip
...
Unzipping SQLite amalgamation src complete
*** Checking for installation of SQLite 3.8.11.1 (extlib/sqlite3) ***

*********************************** Info:
*****************************************
* Using FORKED copy of libCoap located in:
       *
* resource/csdk/connectivity/lib/libcoap-4.1.1
       *
***********************************************************************************
Checking for C++ header file arpa/inet.h... yes
Checking for C++ header file fcntl.h... yes
Checking for C++ header file grp.h... yes
Checking for C++ header file in6addr.h... no
Checking for C++ header file linux/limits.h... yes
Checking for C++ header file memory.h... yes
Checking for C++ header file netdb.h... yes
Checking for C++ header file netinet/in.h... yes
Checking for C++ header file pthread.h... yes
Checking for C++ header file pwd.h... yes
Checking for C++ header file stdlib.h... yes
Checking for C++ header file string.h... yes
Checking for C++ header file strings.h... yes
Checking for C++ header file sys/socket.h... yes
Checking for C++ header file sys/stat.h... yes
Checking for C++ header file sys/time.h... yes
Checking for C++ header file sys/timeb.h... yes
Checking for C++ header file sys/types.h... yes
Checking for C++ header file sys/unistd.h... yes
Checking for C++ header file syslog.h... yes
Checking for C++ header file time.h... yes
Checking for C++ header file unistd.h... yes
Checking for C++ header file uuid/uuid.h... no
Checking for C++ header file windows.h... no
Checking for C++ header file winsock2.h... no
Checking for C++ header file ws2tcpip.h... no
Package uuid was not found in the pkg-config search path.
Perhaps you should add the directory containing `uuid.pc'
to the PKG_CONFIG_PATH environment variable
No package 'uuid' found
OSError: 'pkg-config --cflags --libs uuid' exited 1:
  File "/home/michael_k/iotivity-node-master/iotivity-native/SConstruct",
line 57:
    SConscript(build_dir + 'resource/SConscript')
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 609:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 546:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File
"/home/michael_k/iotivity-node-master/iotivity-native/resource/SConscript",
line 41:
    SConscript('c_common/SConscript')
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 609:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 546:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File
"/home/michael_k/iotivity-node-master/iotivity-native/resource/c_common/SConscript",
line 150:
    env.ParseConfig("pkg-config --cflags --libs uuid")
  File "/usr/lib/scons/SCons/Environment.py", line 1554:
    return function(self, self.backtick(command))
  File "/usr/lib/scons/SCons/Environment.py", line 596:
    raise OSError("'%s' exited %d" % (command, status))
fs.js:765
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory
'/home/michael_k/iotivity-node-master/iotivity-native/out'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at findBins
(/home/michael_k/iotivity-node-master/build-scripts/build-csdk.js:36:16)
    at Object.<anonymous>
(/home/michael_k/iotivity-node-master/build-scripts/build-csdk.js:126:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
make: *** [iotivity-installed] Error 1
make: Leaving directory `/home/michael_k/iotivity-node-master/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(child_process.js:1067:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /home/michael_k/iotivity-node-master
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! iotivity-node@1.2.0-0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iotivity-node@1.2.0-0 install script 'node-gyp
rebuild'.
npm ERR! This is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael_k/iotivity-node-master/npm-debug.log
michael_k@Dell-55RFD12 ~/iotivity-node-master $

**Comment by gabrielschulhof** [comment]
The [installation instructions](https://github.com/otcshare/iotivity-node/#installation) for Linux mention that you need to install the uuid development package (libuuid-devel on Fedora, and uuid-dev on Debian/Ubuntu).

**Comment by micrcx** [comment]
Hi,
In the end I was able to perform the installation and run the client and
server.
Thank you very much, but I want to make one comment: in the instructions
need to specify the minimum version of node.js, and describe in detail the
process of installing additional packages for successful installation for
all operating systems.
Is it so difficult to add a couple of lines such as:

sudo apt-get update
sudo apt-get install uuid-dev
sudo apt-get install libglib2.0-dev

Regards,
Michael K

Server side:
=========
michael_k@Dell-55RFD12 ~/iotivity-node-master $ node
js/server.discoverable.js
Starting OCF stack in server mode
Registering resources
Server ready

Client side:
=========
michael_k@Dell-55RFD12 ~ $ cd iotivity-node-master/
michael_k@Dell-55RFD12 ~/iotivity-node-master $ node js/client.discovery.js
Starting OCF stack in client mode
Issuing discovery request
Discovery response: {
    "devAddr": {
        "adapter": 1,
        "flags": 32,
        "ifindex": 0,
        "port": 44798,
        "addr": "fe80::da25:5173:ca8:c78f%eth2"
    },
    "addr": {
        "adapter": 1,
        "flags": 32,
        "ifindex": 0,
        "port": 44798,
        "addr": "fe80::da25:5173:ca8:c78f%eth2"
    },
    "payload": {
        "type": 1,
        "sid": "54c1c194-e3e2-477d-ad9f-9c1e1abb29b5",
        "resources": [
            {
                "uri": "/oic/sec/doxm",
                "types": [
                    "oic.r.doxm"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/oic/sec/pstat",
                "types": [
                    "oic.r.pstat"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/oic/d",
                "types": [
                    "oic.wk.d"
                ],
                "interfaces": [
                    "oic.if.baseline",
                    "oic.if.r"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/oic/p",
                "types": [
                    "oic.wk.p"
                ],
                "interfaces": [
                    "oic.if.baseline",
                    "oic.if.r"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/BinarySwitchResURI",
                "types": [
                    "oic.r.switch.binary"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 3,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/BinarySwitchResURI2",
                "types": [
                    "oic.r.switch.binary"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 3,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/BinarySwitchResURI3",
                "types": [
                    "oic.r.switch.binary"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 3,
                "secure": false,
                "port": 0
            }
        ]
    },
    "connType": 65568,
    "identity": [],
    "result": 0,
    "sequenceNumber": 16777216,
    "resourceUri": "/oic/res",
    "rcvdVendorSpecificHeaderOptions": []
}
Discovery response: {
    "devAddr": {
        "adapter": 1,
        "flags": 32,
        "ifindex": 0,
        "port": 51113,
        "addr": "fe80::eef4:bbff:fe34:2c05%eth2"
    },
    "addr": {
        "adapter": 1,
        "flags": 32,
        "ifindex": 0,
        "port": 51113,
        "addr": "fe80::eef4:bbff:fe34:2c05%eth2"
    },
    "payload": {
        "type": 1,
        "sid": "cd4a26c8-b4d9-45c8-a28b-044792226b67",
        "resources": [
            {
                "uri": "/oic/sec/doxm",
                "types": [
                    "oic.r.doxm"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": true,
                "port": 53537
            },
            {
                "uri": "/oic/sec/pstat",
                "types": [
                    "oic.r.pstat"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": true,
                "port": 53537
            },
            {
                "uri": "/oic/d",
                "types": [
                    "oic.wk.d"
                ],
                "interfaces": [
                    "oic.if.baseline",
                    "oic.if.r"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/oic/p",
                "types": [
                    "oic.wk.p"
                ],
                "interfaces": [
                    "oic.if.baseline",
                    "oic.if.r"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/a/fan",
                "types": [
                    "core.fan"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            },
            {
                "uri": "/a/light",
                "types": [
                    "core.light"
                ],
                "interfaces": [
                    "oic.if.baseline"
                ],
                "bitmap": 1,
                "secure": false,
                "port": 0
            }
        ]
    },
    "connType": 65568,
    "identity": [],
    "result": 0,
    "sequenceNumber": 16777216,
    "resourceUri": "/oic/res",
    "rcvdVendorSpecificHeaderOptions": []
}
