### ISSUE TITLE
iotivity-node on windows fails

### ISSUE THREAD

**Issue by as2902b** [otcshare/iotivity-node#96]
Unable to find  module 'uuid' at runtime.,

**Comment by gabrielschulhof** [comment]
That's weird. Is this on the maintenance branch?

**Comment by iamsanjeev** [comment]
works fine.

**Comment by gabrielschulhof** [comment]
@iamsanjeev OK, so can I close this issue?

**Comment by gabrielschulhof** [comment]
I guess this is a duplicate of #95, what with the missing libuuid headers.
